name: asdf Setup and Install
description: Setup asdf and install tools

runs:
    using: "composite"
    steps:
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v4.0.1
        continue-on-error: true
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v4.0.1
